/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2016-11-04 19:54:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;

public final class addToCart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


                String strid="",pname,desc,pid="",strname,temp;
                int qty,reqqty;
                double price;
                
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("   \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <script>\r\n");
      out.write("            function validate()\r\n");
      out.write("            {\r\n");
      out.write("               var q=parseInt(document.multi.qty.value);\r\n");
      out.write("               var rq=parseInt(document.multi.reqty.value);\r\n");
      out.write("\r\n");
      out.write("               if(document.multi.reqty.value.length==0)\r\n");
      out.write("               {\r\n");
      out.write("               alert(\"Please Enter a Quantity\");\r\n");
      out.write("                return false;\r\n");
      out.write("               }\r\n");
      out.write("               else if(q < rq)\r\n");
      out.write("               {\r\n");
      out.write("               alert(\"Avaliable quantity is \"+document.multi.qty.value+\" Only...\");\r\n");
      out.write("                return false;\r\n");
      out.write("               }\r\n");
      out.write("               else\r\n");
      out.write("               {\r\n");
      out.write("                self.close();\r\n");
      out.write("                 return true;\r\n");
      out.write("               }\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body background=\"images/img02.png\">\r\n");
      out.write("        <form action=\"addToCart1.jsp\" name=\"multi\" method=\"post\" onsubmit=\"return validate()\">\r\n");
      out.write("            <table width=\"169\">\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                ");

                temp="additems";
                session.setAttribute("temp",temp);
                strname=request.getParameter("strname");
                strid=request.getParameter("strid");
                pname=request.getParameter("pname");
                pid=request.getParameter("pid");
                qty=Integer.parseInt(request.getParameter("qty"));
                price=Double.parseDouble(request.getParameter("price"));
                pname=request.getParameter("pname");
                
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td width=\"112\"><font color=\"#FFFFFF\" size=\"2\"><b>Product Name</b></font></td>\r\n");
      out.write("                    <td><font color=\"#FFFFFF\">");
      out.print(pname);
      out.write("</font></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td width=\"112\"><font color=\"#FFFFFF\" size=\"2\"><b>Required Quantity</b></font></td>\r\n");
      out.write("                    <td><font color=\"#FFFFFF\"><input type=\"text\" size=\"1\" name=\"reqty\" tabindex=\"1\"></font></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <input type=\"hidden\" name=\"qty\" value=\"");
      out.print(qty);
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"pid\" value=\"");
      out.print(pid);
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"strid\" value=\"");
      out.print(strid);
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"strname\" value=\"");
      out.print(strname);
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"price\" value=\"");
      out.print(price);
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"pname\" value=\"");
      out.print(pname);
      out.write("\">\r\n");
      out.write("        <div style=\"position: absolute; width: 140px; height: 44px; z-index: 1; left: 58px; top: 82px\" id=\"layer1\">\r\n");
      out.write("           <input type=\"submit\" value=\"Submit\" name=\"Submit\" tabindex=\"2\">\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>      \r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
