/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2016-11-08 15:12:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import com.shoppingmall.pojo.*;

public final class bill_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


            String strid,pid,strname,ordid,uname,pname,custid,strid1,strname1,prname1;
            int qty,orid,qty1,x;
            double price,totprice,bill,price1,totprice1;
            Connection con;
            Statement st,st1,st2;
            PreparedStatement pst;
            ResultSet rs,rs1,rs2;
            
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.shoppingmall.pojo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "customerLogin.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("   \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>JSP Page</title>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("            ");

            UserBean userbean=(UserBean)session.getAttribute("customer");
            uname=userbean.getUname();
            
            custid=userbean.getCustid();
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","scott","tiger");
            st=con.createStatement();
            try{
            rs=st.executeQuery("select ordid.nextval from dual");
            if(rs.next())
                orid=rs.getInt(1);
            ordid="Order"+orid;
              st1=con.createStatement();
              rs1=st1.executeQuery("select sum(totprice) from prolist");
              if(rs1.next())
              bill=rs1.getInt(1);
              System.out.println("Final Bill : "+bill);
            
             //java.util.Date d1=new java.util.Date();
             pst=con.prepareStatement("insert into bill (ORDID,CUSTID,UNAME,BILL) values(?,?,?,?)");
                pst.setString(1,ordid);
                System.out.println("orderid : "+ordid);
                pst.setString(2,custid);
                System.out.println("custid : "+custid);
                pst.setString(3,uname);
                System.out.println("uname : "+uname);
                pst.setDouble(4,bill);
                System.out.println("bill : "+bill);
                //pst.setDate(5,to_date(sysdate));
                pst.execute();
                rs=st.executeQuery("select * from prolist");
                while(rs.next())
               {
                 strid=rs.getString(1);
                 strname=rs.getString(2);
                 pid=rs.getString(3);
                 pname=rs.getString(4);
                 price=rs.getDouble(5);
                 qty=rs.getInt(6);
                 totprice=rs.getDouble(7);
                 pst=con.prepareStatement("insert into custorder values(?,?,?,?,?,?)");
                 pst.setString(1,ordid);
                 System.out.println("ordid : "+ordid);
                 pst.setString(2,strname);
                 System.out.println("strname : "+strname);
                 pst.setString(3,pname);
                 System.out.println("pname : "+pname);
                 pst.setDouble(4,price);
                 System.out.println("price : "+price);
                 pst.setDouble(5,qty);
                 System.out.println("qty : "+qty);
                 pst.setDouble(6,totprice);
                 System.out.println("totprice : "+totprice);
                 System.out.println("sql statement : "+pst);

                 pst.execute();
                 st2=con.createStatement();
                 st2.executeUpdate("update product set productquantity=productquantity-"+qty+" where strid='"+strid+"' and productid='"+pid+"'");
                //out.print(" "+strname+"  "+pname+"  "+price+"  "+qty+"   "+totprice+"<br>");
                 }


                
      out.write("\r\n");
      out.write("\t\t<div style=\"position: absolute; width: 275px; height: 29px; z-index: 1; left: 550px; top: 239px\" id=\"layer2\">\r\n");
      out.write("\t\t\t<font color=\"#D15803\">\r\n");
      out.write("\t\t\t<b>Your Order Details are </b>\r\n");
      out.write("\t\t\t</font>\r\n");
      out.write("\t\t\t<p><font color=\"#D15803\"><b>Order Id :");
      out.print(ordid);
      out.write("</b></font></p>\r\n");
      out.write("\t\t\t<p><font color=\"#D15803\"><b>Total Order amount\r\n");
      out.write("\t\t\t is : \t");
      out.print(bill);
      out.write("</b></font></p>\r\n");
      out.write("        </div>\r\n");
      out.write("                ");

                st=con.createStatement();
                st.execute("delete from prolist");
                }catch(Exception e){
                	
                	System.out.println("exception" +e);
                	
                    
      out.write("\r\n");
      out.write("                    <div style=\"position: absolute; width: 275px; height: 29px; z-index: 1; left: 550px; top: 237px\" id=\"layer2\">\r\n");
      out.write("                     <font color=\"#D15803\">\r\n");
      out.write("                     <b>Order Already Submitted.. </b>\r\n");
      out.write("\t                \t</font>\r\n");
      out.write("\t                </div>\r\n");
      out.write("               ");
 }
               
      out.write("          \r\n");
      out.write("            <form action=\"completeOrder.do\" method=\"post\">\r\n");
      out.write("    \t\t<div style=\"position: absolute; width: 663px; height: 204px; z-index: 2; left: 550px; top: 342px\" id=\"layer3\">\r\n");
      out.write("\t");


              st2=con.createStatement();
            rs2=st2.executeQuery("select count(ordid) from custorder where ordid='"+ordid+"'");
            if(rs2.next())
                x=rs2.getInt(1);
              st1=con.createStatement();
            rs1=st1.executeQuery("select * from custorder where ordid='"+ordid+"'");
             
      out.write("  \r\n");
      out.write("                                    <table border=\"0\" width=\"100%\" id=\"table1\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"112\"><b><font size=\"2\">Order Details:</font></b></td></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr><td colspan=\"2\">\r\n");
      out.write("                                                    \r\n");
      out.write("                                                For this order id  there are ");
      out.print(x);
      out.write(" orders  </td></tr>\r\n");
      out.write("\r\n");
      out.write("                                            <tr><td colspan=\"2\">    Details are as follows </td></tr>\r\n");
      out.write("                                             <tr><td colspan=\"3\">    ");

                                                int i=0;
                                               while(rs1.next())
                                                {
                                                  strid1=rs1.getString(1);
                                                  strname1=rs1.getString(2);
                                                  prname1=rs1.getString(3);
                                                  price1=rs1.getInt(4);
                                                  qty1=rs1.getInt(5);
                                                  totprice1=rs1.getInt(6);
                                                  i++;
                                               
      out.write("\r\n");
      out.write("                                               Order ");
      out.print(i);
      out.write(" details are:::\r\n");
      out.write("                                             Store name =  ");
      out.print(strname1);
      out.write(", Product name= ");
      out.print(prname1);
      out.write(", Price = ");
      out.print(price);
      out.write(", Quantity = ");
      out.print(qty);
      out.write(", TotalPrice = ");
      out.print(totprice);
      out.write("\r\n");
      out.write("                                            ");

	                                }
	                            
      out.write("\t\t\t                                   \r\n");
      out.write("                        </td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"112\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"112\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"submit\" value=\"submit\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
