/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2016-11-05 23:10:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registerStore_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "index1.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("   \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction checkStoreForm() {\r\n");
      out.write("\t\tvar error = 0;\r\n");
      out.write("\t\tvar sname = document.multi.strname.value;\r\n");
      out.write("\t\tif (sname == '') {\r\n");
      out.write("\t\t\terror += 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tvar username = document.multi.uname.value;\r\n");
      out.write("\r\n");
      out.write("\t\tif (username == '') {\r\n");
      out.write("\t\t\terror += 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tre = /^\\w+$/;\r\n");
      out.write("\t\tif (!re.test(username)) {\r\n");
      out.write("\t\t\talert(\"Error: Username must contain only letters, numbers and underscores!\");\r\n");
      out.write("\t\t\terror += 1;\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar userpword = document.multi.pwd.value;\r\n");
      out.write("\t\tif (userpword == '') {\r\n");
      out.write("\t\t\terror += 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (userpword == username) {\r\n");
      out.write("\t\t\talert(\"Error: Password must be different from Username!\");\r\n");
      out.write("\t\t\terror += 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tre = /[0-9]/;\r\n");
      out.write("\t\tif (!re.test(userpword)) {\r\n");
      out.write("\t\t\talert(\"Error: password must contain at least one number (0-9)!\");\r\n");
      out.write("\t\t\terror += 1;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tre = /[a-z]/;\r\n");
      out.write("\t\tif (!re.test(userpword)) {\r\n");
      out.write("\t\t\talert(\"Error: password must contain at least one lowercase letter (a-z)!\");\r\n");
      out.write("\t\t\terror += 1;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tre = /[A-Z]/;\r\n");
      out.write("\t\tif (!re.test(userpword)) {\r\n");
      out.write("\t\t\talert(\"Error: password must contain at least one uppercase letter (A-Z)!\");\r\n");
      out.write("\t\t\terror += 1;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar numbers = /^[0-9]+$/;\r\n");
      out.write("\r\n");
      out.write("\t\tvar cmobile = document.multi.bmobile.value;\r\n");
      out.write("\t\tif (cmobile == '') {\r\n");
      out.write("\t\t\terror += 1;\r\n");
      out.write("\t\t} else if (!(cmobile.match(numbers))) {\r\n");
      out.write("\t\t\talert('Mobile Should Accept Only Numbers');\r\n");
      out.write("\t\t\terror += 1;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar bphone = document.multi.bphn.value;\r\n");
      out.write("\t\tif (cmobile == '') {\r\n");
      out.write("\t\t\terror += 1;\r\n");
      out.write("\t\t} else if (!(bphone.match(numbers))) {\r\n");
      out.write("\t\t\talert('Business Phone Should Accept Only Numbers');\r\n");
      out.write("\t\t\terror += 1;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar filter = /^([\\w-]+(?:\\.[\\w-]+)*)@((?:[\\w-]+\\.)*\\w[\\w-]{0,66})\\.([a-z]{2,6}(?:\\.[a-z]{2})?)$/i\r\n");
      out.write("\t\tvar cemail = document.multi.bemail.value;\r\n");
      out.write("\t\tif (cemail == '') {\r\n");
      out.write("\t\t\terror += 1;\r\n");
      out.write("\t\t} else if (!filter.test(cemail)) {\r\n");
      out.write("\t\t\talert('Not a valid Email');\r\n");
      out.write("\t\t\terror += 1;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar address1 = document.multi.baddr.value;\r\n");
      out.write("\t\tif (address1 == '') {\r\n");
      out.write("\t\t\terror += 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (error == 0) {\r\n");
      out.write("\t\t\tdocument.submit();\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\tvar div = document.getElementById(\"alertDiv\");\r\n");
      out.write("\t\t\tdiv.innerHTML = \"All Fields Are Mandatory\";\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction allnumeric(inputtxt) {\r\n");
      out.write("\t\tvar numbers = /^[0-9]+$/;\r\n");
      out.write("\t\tif (inputtxt.value.match(numbers)) {\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert('Please Allow numeric characters only');\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"registerStore.do\" method=post name=multi\r\n");
      out.write("\t\tonsubmit=\"return checkStoreForm()\">\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"position: absolute; width: 433px; height: 152px; z-index: 1; left: 600px; top: 273px\"\r\n");
      out.write("\t\t\tid=\"layer1\">\r\n");
      out.write("\t\t\t<table border=\"0\" width=\"100%\" id=\"table1\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"41%\"><font face=\"Arial Narrow\" color=\"#666600\">Name\r\n");
      out.write("\t\t\t\t\t\t\tof Store</font></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"56%\"><font face=\"Trebuchet MS\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" name=\"strname\" size=\"20\"></font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"41%\"><font face=\"Arial Narrow\" color=\"#666600\">User\r\n");
      out.write("\t\t\t\t\t\t\tName</font></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"56%\"><font face=\"Trebuchet MS\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" name=\"uname\" size=\"20\"></font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"41%\"><font face=\"Arial Narrow\" color=\"#666600\">Password</font></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"56%\"><font face=\"Trebuchet MS\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"password\" name=\"pwd\" size=\"20\"></font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><font face=\"Arial Narrow\" color=\"#666600\">Store\r\n");
      out.write("\t\t\t\t\t\t\tCategory</font></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"56%\"><font face=\"Trebuchet MS\"> <select\r\n");
      out.write("\t\t\t\t\t\t\tsize=\"1\" name=\"strType\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value=\"Select\">Select</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Dollor Store\">Dollar Store</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Branded Store\">Branded Store</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Department Store\">Department Store</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Super Market\">Super Market</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Hyper Market\">Hyper Market</option>\r\n");
      out.write("\t\t\t\t\t\t</select></font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><font face=\"Arial Narrow\" color=\"#666600\">Business\r\n");
      out.write("\t\t\t\t\t\t\tAddress</font></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"56%\"><textarea rows=\"2\" name=\"baddr\" cols=\"18\"></textarea></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><font face=\"Arial Narrow\" color=\"#666600\">Business\r\n");
      out.write("\t\t\t\t\t\t\tPhone Number</font></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"56%\"><font face=\"Trebuchet MS\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" name=\"bphn\" size=\"20\"></font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><font face=\"Arial Narrow\" color=\"#666600\">Business\r\n");
      out.write("\t\t\t\t\t\t\tMobile Number</font></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"56%\"><font face=\"Trebuchet MS\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" name=\"bmobile\" size=\"20\"></font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><font face=\"Arial Narrow\" color=\"#666600\">business\r\n");
      out.write("\t\t\t\t\t\t\tEmail ID</font></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"56%\"><font face=\"Trebuchet MS\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" name=\"bemail\" size=\"20\"></font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" align=\"center\"><div id=alertDiv\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: red\"></div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"position: absolute; width: 150px; height: 19px; z-index: 5; left: 751px; top: 519px\"\r\n");
      out.write("\t\t\tid=\"layer5\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Submit\">&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<input type=\"reset\" value=\"Reset\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"position: absolute; width: 319px; height: 36px; z-index: 2; left: 700px; top: 192px\"\r\n");
      out.write("\t\t\tid=\"layer2\">\r\n");
      out.write("\t\t\t<b><font face=\"Bell MT\" size=\"5\" color=\"#D15803\">Store\r\n");
      out.write("\t\t\t\t\tRegistration</font></b>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
