/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2016-11-04 01:06:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class updateStoreDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "storeManagerLogin.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("   \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("          <script>\r\n");
      out.write("          function checkStoreForm() {\r\n");
      out.write("      \t\tvar error = 0;\r\n");
      out.write("      \t\tvar sname = document.multi.strname.value;\r\n");
      out.write("      \t\tif (sname == '') {\r\n");
      out.write("      \t\t\terror += 1;\r\n");
      out.write("      \t\t}\r\n");
      out.write("      \t\t\r\n");
      out.write("\r\n");
      out.write("      \t\tvar username = document.multi.uname.value;\r\n");
      out.write("\r\n");
      out.write("      \t\tif (username == '') {\r\n");
      out.write("      \t\t\terror += 1;\r\n");
      out.write("      \t\t}\r\n");
      out.write("      \t\tre = /^\\w+$/;\r\n");
      out.write("      \t\tif (!re.test(username)) {\r\n");
      out.write("      \t\t\talert(\"Error: Username must contain only letters, numbers and underscores!\");\r\n");
      out.write("      \t\t\terror += 1;\r\n");
      out.write("      \t\t\r\n");
      out.write("\r\n");
      out.write("      \t\t}\r\n");
      out.write("\r\n");
      out.write("      \t\tvar userpword = document.multi.pwd.value;\r\n");
      out.write("      \t\tif (userpword == '') {\r\n");
      out.write("      \t\t\terror += 1;\r\n");
      out.write("      \t\t}\r\n");
      out.write("      \t\tif (userpword == username) {\r\n");
      out.write("      \t\t\talert(\"Error: Password must be different from Username!\");\r\n");
      out.write("      \t\t\terror += 1;\r\n");
      out.write("      \t\t}\r\n");
      out.write("      \t\tre = /[0-9]/;\r\n");
      out.write("      \t\tif (!re.test(userpword)) {\r\n");
      out.write("      \t\t\talert(\"Error: password must contain at least one number (0-9)!\");\r\n");
      out.write("      \t\t\terror += 1;\r\n");
      out.write("      \t\t\t\r\n");
      out.write("      \t\t}\r\n");
      out.write("      \t\tre = /[a-z]/;\r\n");
      out.write("      \t\tif (!re.test(userpword)) {\r\n");
      out.write("      \t\t\talert(\"Error: password must contain at least one lowercase letter (a-z)!\");\r\n");
      out.write("      \t\t\terror += 1;\r\n");
      out.write("      \t\t\t\r\n");
      out.write("      \t\t}\r\n");
      out.write("      \t\tre = /[A-Z]/;\r\n");
      out.write("      \t\tif (!re.test(userpword)) {\r\n");
      out.write("      \t\t\talert(\"Error: password must contain at least one uppercase letter (A-Z)!\");\r\n");
      out.write("      \t\t\terror += 1;\r\n");
      out.write("      \t\t\t\r\n");
      out.write("      \t\t}\r\n");
      out.write("\r\n");
      out.write("      \t\tvar numbers = /^[0-9]+$/;\r\n");
      out.write("\r\n");
      out.write("      \t\tvar cmobile = document.multi.bmobile.value;\r\n");
      out.write("      \t\tif (cmobile == '') {\r\n");
      out.write("      \t\t\terror += 1;\r\n");
      out.write("      \t\t} else if (!(cmobile.match(numbers))) {\r\n");
      out.write("      \t\t\talert('Mobile Should Accept Only Numbers');\r\n");
      out.write("      \t\t\terror += 1;\r\n");
      out.write("      \t\t\t\r\n");
      out.write("      \t\t}\r\n");
      out.write("      \t\t\r\n");
      out.write("      \t\tvar bphone = document.multi.bphn.value;\r\n");
      out.write("      \t\tif (cmobile == '') {\r\n");
      out.write("      \t\t\terror += 1;\r\n");
      out.write("      \t\t} else if (!(bphone.match(numbers))) {\r\n");
      out.write("      \t\t\talert('Business Phone Should Accept Only Numbers');\r\n");
      out.write("      \t\t\terror += 1;\r\n");
      out.write("      \t\t\t\r\n");
      out.write("      \t\t}\r\n");
      out.write("\r\n");
      out.write("      \t\tvar filter = /^([\\w-]+(?:\\.[\\w-]+)*)@((?:[\\w-]+\\.)*\\w[\\w-]{0,66})\\.([a-z]{2,6}(?:\\.[a-z]{2})?)$/i\r\n");
      out.write("      \t\tvar cemail = document.multi.bemail.value;\r\n");
      out.write("      \t\tif (cemail == '') {\r\n");
      out.write("      \t\t\terror += 1;\r\n");
      out.write("      \t\t} else if (!filter.test(cemail)) {\r\n");
      out.write("      \t\t\talert('Not a valid Email');\r\n");
      out.write("      \t\t\terror += 1;\r\n");
      out.write("      \t\t\t\r\n");
      out.write("      \t\t}\r\n");
      out.write("      \t\tvar address1 = document.multi.baddr.value;\r\n");
      out.write("      \t\tif (address1 == '') {\r\n");
      out.write("      \t\t\terror += 1;\r\n");
      out.write("      \t\t}\r\n");
      out.write("      \t\t\r\n");
      out.write("      \t\tif (error == 0) {\r\n");
      out.write("      \t\t\tdocument.submit();\r\n");
      out.write("      \t\t\treturn true;\r\n");
      out.write("      \t\t} \r\n");
      out.write("      \t\telse {\r\n");
      out.write("      \t\t\tvar div = document.getElementById(\"alertDiv\");\r\n");
      out.write("      \t\t\tdiv.innerHTML = \"All Fields Are Mandatory\";\r\n");
      out.write("      \t\t\treturn false;\r\n");
      out.write("\r\n");
      out.write("      \t\t}\r\n");
      out.write("      \t}\r\n");
      out.write("\r\n");
      out.write("      \tfunction allnumeric(inputtxt) {\r\n");
      out.write("      \t\tvar numbers = /^[0-9]+$/;\r\n");
      out.write("      \t\tif (inputtxt.value.match(numbers)) {\r\n");
      out.write("\r\n");
      out.write("      \t\t\treturn true;\r\n");
      out.write("      \t\t} else {\r\n");
      out.write("      \t\t\talert('Please Allow numeric characters only');\r\n");
      out.write("      \t\t\treturn false;\r\n");
      out.write("      \t\t}\r\n");
      out.write("      \t}\r\n");
      out.write("          </script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <form action=\"updateStoreDetails.do\" method=\"post\" name=multi onsubmit=\"return checkStoreForm()\">\r\n");
      out.write("            \r\n");
      out.write("            <div style=\"position: absolute; width: 535px; height: 54px; z-index: 1; left: 590px; top: 266px\" id=\"layer1\">\r\n");
      out.write("                <div align=\"center\">\r\n");
      out.write("                <table border=\"0\" width=\"73%\" id=\"table1\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"170\"><b><font size=\"2\">Store ID</font></b></td>\r\n");
      out.write("                        <td><input type=\"text\" name=\"storeId\" size=\"20\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${strBean.storeId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"170\"><b><font size=\"2\">Store Name</font></b></td>\r\n");
      out.write("                        <td><input type=\"text\" name=\"strname\" size=\"20\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${strBean.strname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"170\"><b><font size=\"2\">User Name</font></b></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                        <input type=\"text\" name=\"uname\" size=\"20\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${strBean.uname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"170\"><b><font size=\"2\">Password</font></b></td>\r\n");
      out.write("                        <td><input type=\"password\" name=\"pwd\" size=\"20\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${strBean.pwd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                   <tr>\r\n");
      out.write("                        <td><b><font size=\"2\">Store Category</font></b></td>\r\n");
      out.write("                        <td width=\"54%\">\r\n");
      out.write("                        <select size=\"1\" name=\"strType\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${strBean.strType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        <option selected value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${strBean.strType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${strBean.strType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</option>\r\n");
      out.write("                        <option value=\"Dollor Store\">Dollar Store</option>\r\n");
      out.write("                        <option value=\"Branded Store\">Branded Store</option>\r\n");
      out.write("                        <option value=\"Department Store\">Department Store\r\n");
      out.write("                        </option>\r\n");
      out.write("                        <option value=\"Super Market\">Super Market</option>\r\n");
      out.write("                        <option value=\"Hyper Market\">Hyper Market</option>\r\n");
      out.write("                        </select></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"170\"><b><font size=\"2\">Business Address</font></b></td>\r\n");
      out.write("                        <td><textarea rows=\"2\" name=\"baddr\" cols=\"17\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${strBean.baddr }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"170\"><b><font size=\"2\">Business Phone</font></b></td>\r\n");
      out.write("                        <td><input type=\"text\" name=\"bphn\" size=\"20\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${strBean.bphn }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"170\"><b><font size=\"2\">Mobile</font></b></td>\r\n");
      out.write("                        <td><input type=\"text\" name=\"bmobile\" size=\"20\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${strBean.bmobile }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"170\"><b><font size=\"2\">Email ID</font></b></td>\r\n");
      out.write("                        <td><input type=\"text\" name=\"bemail\" size=\"20\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${strBean.bemail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>               \r\n");
      out.write("            \t</div>\r\n");
      out.write("            </div>\t  \r\n");
      out.write("            \r\n");
      out.write("             <div style=\"position: absolute; width: 169px; height: 36px; z-index: 1; left: 750px; top: 533px\" id=\"layer7\">&nbsp; \r\n");
      out.write("                    <input type=\"submit\" value=\"Update\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                    <input type=\"reset\" value=\"Reset\">&nbsp;\r\n");
      out.write("                </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
