/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2016-11-04 21:41:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.shoppingmall.pojo.*;

public final class viewCart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


            String strid,pid,strname,ordid,uname,pname;
            int qty,reqty;
            double price,totprice,bill;
            static double bil=0,i=0;
            Connection con;
            Statement st;
            PreparedStatement pst;
            ResultSet rs;
            
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.shoppingmall.pojo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "customerLogin.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("   \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <script LANGUAGE=\"JavaScript\">\r\n");
      out.write("            function popUp(URL) {\r\n");
      out.write("            day = new Date();\r\n");
      out.write("            id = day.getTime();\r\n");
      out.write("            eval(\"page\" + id + \" = window.open(URL, '\" + id + \"', 'toolbar=0,scrollbars=1,location=0,statusbar=1,menubar=0,resizable=1,width=400,height=400,left = 362,top = 234');\");\r\n");
      out.write("            }\r\n");
      out.write("            function confirmDelete(delUrl) {\r\n");
      out.write("              if (confirm(\"Are you sure you want to delete\")) {\r\n");
      out.write("                document.location = delUrl;\r\n");
      out.write("              }\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <form action=\"bill.jsp\" method=\"post\">\r\n");
      out.write("             ");
      out.write("\r\n");
      out.write("            ");

            UserBean userbean=(UserBean)session.getAttribute("customer");
            uname=userbean.getUname();
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","scott","tiger");
            st=con.createStatement();
            rs=st.executeQuery("select * from prolist");
            
      out.write("\r\n");
      out.write("           <div style=\"position: absolute; width: 535px; height: 24px; z-index: 1; left: 550px; top: 204px\" id=\"layer1\">\r\n");
      out.write("\t\t\t\t<font color=\"#B9B900\">\r\n");
      out.write("\t\t\t\t<b><marquee behavior=\"alternate\">Welcome to ");
      out.print(uname);
      out.write(", Your Cart Details are given Below</marquee></b>\r\n");
      out.write("\t\t\t\t</font>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("            <div style=\"position: absolute; width: 535px; height: 54px; z-index: 1; left: 550px; top: 266px\" id=\"layer1\">\r\n");
      out.write("                <table border=\"1\" width=\"100%\" id=\"table1\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td align=\"center\"><b><font size=\"2\">Store Name</font></b></td>\r\n");
      out.write("                        <td align=\"center\"><b><font size=\"2\">Product Name</font></b></td>\r\n");
      out.write("                        <td align=\"center\"><b><font size=\"2\">Price</font></b></td>\r\n");
      out.write("                        <td align=\"center\"><b><font size=\"2\">Quantity</font></b></td>\r\n");
      out.write("                        <td align=\"center\"><b><font size=\"2\">Total Price</font></b></td>\r\n");
      out.write("                        <td align=\"center\"><b><font size=\"2\">Action</font></b></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                    while(rs.next())
                    {
                    	strid=rs.getString(1);
                        strname=rs.getString(2);
                        pid=rs.getString(3);
                        pname=rs.getString(4);
                        price=rs.getDouble(5);
                        reqty=rs.getInt(6);
                        totprice=rs.getDouble(7);
                        qty=rs.getInt(8);
                    
                    
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td align=\"center\"><font size=\"2\">");
      out.print(strname);
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\"><font size=\"2\">");
      out.print(pname);
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\"><font size=\"2\">");
      out.print(price);
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\"><font size=\"2\">");
      out.print(reqty);
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\"><font size=\"2\">");
      out.print(totprice);
      out.write("</font></td>\r\n");
      out.write("                        \t<td align=\"center\"><b><a HREF=\"javascript:popUp('editOrder.jsp?pid=");
      out.print(pid);
      out.write("&pname=");
      out.print(pname);
      out.write("&price=");
      out.print(price);
      out.write("&reqty=");
      out.print(reqty);
      out.write("&strid=");
      out.print(strid);
      out.write("&strname=");
      out.print(strname);
      out.write("&qty=");
      out.print(qty);
      out.write("')\">\r\n");
      out.write("\t\t\t\t\t\t\t<font size=\"2\">Edit</font></a></b><font size=\"2\">\r\n");
      out.write("                                /\r\n");
      out.write("</font>\r\n");
      out.write("<a href=\"javascript:confirmDelete('delOrderFrmCart.jsp?pid=");
      out.print(pid);
      out.write("')\"><font size=\"2\">Delete</font></a></td>\r\n");
      out.write("                        ");

                        }
                        
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr><td colspan=\"6\" align=\"center\"><input type=\"submit\" value=\"Submit Order\" name=\"B1\"></td></tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("    \t<div style=\"position: absolute; width: 100px; height: 32px; z-index: 5; left: 650px; top: 235px\" id=\"layer5\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("    </form>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
